name: "Dependency Review"
on:
  pull_request:
    branches:
      - main
      - release-*
      - v3
  merge_group:

concurrency:
  group: ${{ github.ref_name }}-deps-review
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-22.04
    permissions:
      contents: read # for actions/checkout
      pull-requests: write # for actions/dependency-review-action to post comments
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: "Dependency Review"
        uses: actions/dependency-review-action@72eb03d02c7872a771aacd928f3123ac62ad6d3a # v4.3.3
        with:
          config-file: "nginxinc/k8s-common/dependency-review-config.yml@main"
